In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame
pd.set_option('display.max_columns', None)

In [25]:
data=pd.read_csv('/Users/shkim/Desktop/data/dataset.csv')
data

/var/folders/q2/s0xlwpx90gn672csdxd2vgnh0000gn/T/ipykernel_26496/3969864309.py:1: DtypeWarning: Columns (93) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('/Users/shkim/Desktop/data/dataset.csv')

,Unnamed: 0.1,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,fielder_2,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,pitcher.1,fielder_2.1,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
0,0,0.0,FC,2022-10-05,94.4,-0.56,6.09,"Burnes, Corbin",672695,669203,field_out,hit_into_play,NaN,NaN,NaN,NaN,3.0,Geraldo Perdomo lines out to first baseman Row...,R,L,R,MIL,AZ,X,3.0,line_drive,3,2,2022,0.63,0.66,0.47,2.96,NaN,NaN,NaN,2,3,Top,155.26,162.84,NaN,NaN,605170,NaN,NaN,1.274985,-137.483995,-3.970761,7.729784,28.554242,-23.099677,3.34,1.61,129.0,90.2,9.0,94.4,2859.0,6.1,661227,669203,605170,642133,649966,607054,642715,669374,669003,621438,54.38,0.554,0.502,0.0,1.0,0.0,0.0,4.0,17,6,Cutter,0,0,0,0,0,0,0,0,Infield shift,Standard,159.0,0.011,-0.116
1,1,1.0,CU,2022-10-05,81.5,-0.37,6.10,"Burnes, Corbin",672695,669203,NaN,ball,NaN,NaN,NaN,NaN,13.0,Geraldo Perdomo lines out to first baseman Row...,R,L,R,MIL,AZ,B,NaN,NaN,2,2,2022,1.02,-0.79,-0.70,0.84,NaN,NaN,NaN,2,3,Top,NaN,NaN,NaN,NaN,605170,NaN,NaN,-2.704095,-118.611106,-3.646629,10.168174,24.177384,-39.088656,3.33,1.54,NaN,NaN,NaN,81.2,2887.0,6.2,661227,669203,605170,642133,649966,607054,642715,669374,669003,621438,54.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,5,Curveball,0,0,0,0,0,0,0,0,Infield shift,Standard,43.0,0.000,0.033
2,2,2.0,SI,2022-10-05,97.0,-0.39,6.08,"Burnes, Corbin",672695,669203,NaN,ball,NaN,NaN,NaN,NaN,12.0,Geraldo Perdomo lines out to first baseman Row...,R,L,R,MIL,AZ,B,NaN,NaN,1,2,2022,-0.93,1.02,2.09,2.88,NaN,NaN,NaN,2,3,Top,NaN,NaN,NaN,NaN,605170,NaN,NaN,8.765445,-140.947995,-5.312010,-14.419883,33.229356,-17.568159,3.33,1.51,NaN,NaN,NaN,97.0,2598.0,6.4,661227,669203,605170,642133,649966,607054,642715,669374,669003,621438,54.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,4,Sinker,0,0,0,0,0,0,0,0,Infield shift,Standard,191.0,0.000,0.014
3,3,3.0,CH,2022-10-05,90.4,-0.60,5.80,"Burnes, Corbin",672695,669203,NaN,foul,NaN,NaN,NaN,NaN,14.0,Geraldo Perdomo lines out to first baseman Row...,R,L,R,MIL,AZ,S,NaN,NaN,1,1,2022,-1.04,0.84,0.09,1.36,NaN,NaN,NaN,2,3,Top,NaN,NaN,NaN,NaN,605170,NaN,NaN,3.956150,-131.306712,-6.811385,-12.875134,31.792983,-21.155612,3.34,1.61,2.0,68.2,-33.0,89.8,2170.0,6.4,661227,669203,605170,642133,649966,607054,642715,669374,669003,621438,54.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,3,Changeup,0,0,0,0,0,0,0,0,Standard,Standard,212.0,0.000,-0.023
4,4,4.0,FC,2022-10-05,95.5,-0.42,6.07,"Burnes, Corbin",672695,669203,NaN,ball,NaN,NaN,NaN,NaN,14.0,Geraldo Perdomo lines out to first baseman Row...,R,L,R,MIL,AZ,B,NaN,NaN,0,1,2022,0.63,0.80,1.69,1.42,NaN,NaN,NaN,2,3,Top,NaN,NaN,NaN,NaN,605170,NaN,NaN,4.131088,-138.945857,-8.452479,7.342463,28.639172,-20.225283,3.33,1.43,NaN,NaN,NaN,95.8,2801.0,6.3,661227,669203,605170,642133,649966,607054,642715,669374,669003,621438,54.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,2,Cutter,0,0,0,0,0,0,0,0,Standard,Standard,172.0,0.000,0.011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,57758,1536.0,SL,2022-04-17,82.2,0.73,6.27,"Ashby, Aaron",666185,676879,field_out,hit_into_play,NaN,NaN,NaN,NaN,14.0,Dylan Carlson flies out to right fielder Andre...,R,R,L,MIL,STL,X,9.0,fly_ball,1,2,2022,-0.58,-0.50,0.84,2.33,NaN,NaN,NaN,0,1,Top,197.95,88.82,NaN,NaN,553882,NaN,NaN,1.349900,-119.710069,-1.401711,-5.835754,23.733225,-36.959569,3.47,1.59,324.0,91.1,26.0,81.1,2632.0,5.5,661226,676879,553882,642133,543939,607054,642715,592885,621438,457705,54.97,0.137,0.173,0.0,1.0,0.0,0.0,3.0,1,5,Slider,0,0,0,0,0,0,0,0,Standard,Standard,334.0,0.022,-0.158
310319,57759,1537.0,FF,2022-04-17,94.7,0.27,6.48,"Ashby, Aaron",666185,676879,NaN,foul,NaN,NaN,NaN,NaN,12.0,Dylan Carlson flies out to right fielder Andre...,R,R,L,MIL,STL,S,NaN,NaN,1,2,2022,0.91,1.14,1.15,3.25,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,553882,NaN,NaN,0.266802,-137.840260,-5.207271,11.524297,31.935077,-16.719401,3.47,1.59,NaN,NaN,NaN,92.7,2143.0,5.2,661226,676879,553882,642133,543939,607054,642715,592885,621438,457705,55.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,145.0,0.000,0.0
310320,57760,1538.0,SL,2022-04-17,82.0,0.77,6.28,"Ashby, Aaron",666185,676879,NaN,called_strike,NaN,NaN,NaN,NaN,4.0,Dylan Carlson flies out to right fielder Andre...,R,R,L,MIL,STL,S,NaN,NaN,1,1,2022,-1.16,0.03,-0.40,2.27,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,553882,NaN,NaN,-0.382884,-119.302912,-2.475940,-10.917350,25.586103,-31.599245,3.09,1.31,NaN,NaN,NaN,80.2,2519.0,5.3,661226,676879,553882,642133,543939,607054,642715,592885,621438,457705,55.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,Slider,0,0,0,0,0,0,0,0,Standard,Standard,338.0,0.000,-0.054
310321,57761,1539.0,SL,2022-04-17,84.0,0.75,6.31,"Ashby, Aaron",666185,676879,NaN,ball,NaN,NaN,NaN,NaN,13.0,Dylan Carlson flies out to right fielder Andre...,R,R,L,MIL,STL,B,NaN,NaN,0,1,2022,-0.83,-0.27,-1.29,0.84,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,553882,NaN,NaN,-3.031336,-122.195726,-5.635994,-7.631446,25.356375,-33.908810,3.25,1.39,NaN,NaN,NaN,82.7,2618.0,5.6,661226,676879,553882,642133,543939,607054,642715,592885,621438,457705,54.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Slider,0,0,0,0,0,0,0,0,Standard,Standard,340.0,0.000,0.025
310322,57762,1540.0,SI,2022-04-17,93.9,0.64,6.52,"Ashby, Aaron",666185,676879,NaN,called_strike,NaN,NaN,NaN,NaN,3.0,Dylan Carlson flies out to right fielder Andre...,R,R,L,MIL,STL,S,NaN,NaN,0,0,2022,1.14,1.14,0.71,2.94,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,553882,NaN,NaN,-2.297997,-136.664552,-5.979827,14.844319,29.513166,-16.718326,3.22,1.36,NaN,NaN,NaN,92.1,1973.0,5.2,661226,676879,553882,642133,543939,607054,642715,592885,621438,457705,55.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,Sinker,0,0,0,0,0,0,0,0,Standard,Standard,135.0,0.000,-0.034

In [16]:
data=pd.read_csv('/Users/shkim/Desktop/data/dataset.csv')
cutoff=data[['pitch_name','game_date','batter','pitcher','player_name','description','events','zone','stand','p_throws','type','plate_x','plate_z','inning','pitch_number','home_team','away_team','inning_topbot']]
cutoff.inning_topbot.unique()

/var/folders/q2/s0xlwpx90gn672csdxd2vgnh0000gn/T/ipykernel_26496/1686814657.py:1: DtypeWarning: Columns (93) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('/Users/shkim/Desktop/data/dataset.csv')

array(['Top', 'Bot'], dtype=object)

In [11]:
cutoff=data[['pitch_name','game_date','batter','pitcher','player_name','description','events','zone','stand','p_throws','plate_x','plate_z','inning','pitch_number','home_team','away_team','inning_topbot']]
cutoff

,pitch_name,game_date,batter,pitcher,player_name,description,events,zone,stand,p_throws,plate_x,plate_z,inning,pitch_number,home_team,away_team,inning_topbot
0,Cutter,2022-10-05,672695,669203,"Burnes, Corbin",hit_into_play,field_out,3.0,L,R,0.47,2.96,3,6,MIL,AZ,Top
1,Curveball,2022-10-05,672695,669203,"Burnes, Corbin",ball,NaN,13.0,L,R,-0.70,0.84,3,5,MIL,AZ,Top
2,Sinker,2022-10-05,672695,669203,"Burnes, Corbin",ball,NaN,12.0,L,R,2.09,2.88,3,4,MIL,AZ,Top
3,Changeup,2022-10-05,672695,669203,"Burnes, Corbin",foul,NaN,14.0,L,R,0.09,1.36,3,3,MIL,AZ,Top
4,Cutter,2022-10-05,672695,669203,"Burnes, Corbin",ball,NaN,14.0,L,R,1.69,1.42,3,2,MIL,AZ,Top
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,Slider,2022-04-17,666185,676879,"Ashby, Aaron",hit_into_play,field_out,14.0,R,L,0.84,2.33,1,5,MIL,STL,Top
310319,4-Seam Fastball,2022-04-17,666185,676879,"Ashby, Aaron",foul,NaN,12.0,R,L,1.15,3.25,1,4,MIL,STL,Top
310320,Slider,2022-04-17,666185,676879,"Ashby, Aaron",called_strike,NaN,4.0,R,L,-0.40,2.27,1,3,MIL,STL,Top
310321,Slider,2022-04-17,666185,676879,"Ashby, Aaron",ball,NaN,13.0,R,L,-1.29,0.84,1,2,MIL,STL,Top
310322,Sinker,2022-04-17,666185,676879,"Ashby, Aaron",called_strike,NaN,3.0,R,L,0.71,2.94,1,1,MIL,STL,Top

In [26]:
#p_throws change
cutoff.loc[cutoff['p_throws'] == 'L', 'p_throws'] = 1
cutoff.loc[cutoff['p_throws'] == 'R', 'p_throws'] = 2

#stand
cutoff.loc[cutoff['stand'] == 'L', 'stand'] = 1
cutoff.loc[cutoff['stand'] == 'R', 'stand'] = 2


#pitch_type
cutoff['pitch_name'].fillna('N', inplace=True) # nan을 N으로 수정
fastball = ['Cutter','4-Seam Fastball','Split-Finger' ] #Fastball
for keyword in fastball:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '1'


curve= ['Knuckle Curve','Curveball', 'Slow Curve']#Curve
for keyword in curve:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '2'


slider= ['Slider','Slurve','Sweeper']#Breaking ball
for keyword in slider:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '3'

changeup= ['Changeup']#Breaking ball
for keyword in changeup:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '4'

sinker= ['Sinker']#sinker
for keyword in sinker:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '5'


etc= [ 'Pitch Out', 'N']#etc
for keyword in etc:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['pitch_name'].str.contains(keyword), 'pitch_name'] = '6'

#description
ball = ['ball', 'blocked_ball','hit_by_pitch'] #ball
for keyword in ball:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['description'].str.contains(keyword), 'description'] = 'B'

strike = ['called_strike', 'foul_tip','missed_bunt','swinging_strike','swinging_strike_blocked','foul','foul_bunt' ] #strike
for keyword in strike:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['description'].str.contains(keyword), 'description'] = 'S'

in_play = ['hit_into_play' ] #in-play
for keyword in in_play:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['description'].str.contains(keyword), 'description'] = 'X'

nothing = [ 'pitchout' ]
for keyword in ball:
    # 해당 키워드를 포함하는 행을 선택하여 값을 변경
    cutoff.loc[cutoff['description'].str.contains(keyword), 'description'] = 'P'

cutoff

,pitch_name,game_date,batter,pitcher,player_name,description,events,zone,stand,p_throws,type,plate_x,plate_z,inning,pitch_number,home_team,away_team,inning_topbot,team
0,1,2022-10-05,672695,669203,"Burnes, Corbin",X,field_out,3.0,1,2,X,0.47,2.96,3,6,MIL,,Top,MIL
1,2,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,13.0,1,2,B,-0.70,0.84,3,5,MIL,,Top,MIL
2,5,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,12.0,1,2,B,2.09,2.88,3,4,MIL,,Top,MIL
3,4,2022-10-05,672695,669203,"Burnes, Corbin",S,NaN,14.0,1,2,S,0.09,1.36,3,3,MIL,,Top,MIL
4,1,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,14.0,1,2,B,1.69,1.42,3,2,MIL,,Top,MIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,3,2022-04-17,666185,676879,"Ashby, Aaron",X,field_out,14.0,2,1,X,0.84,2.33,1,5,MIL,,Top,MIL
310319,1,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,12.0,2,1,S,1.15,3.25,1,4,MIL,,Top,MIL
310320,3,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,4.0,2,1,S,-0.40,2.27,1,3,MIL,,Top,MIL
310321,3,2022-04-17,666185,676879,"Ashby, Aaron",B,NaN,13.0,2,1,B,-1.29,0.84,1,2,MIL,,Top,MIL
310322,5,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,3.0,2,1,S,0.71,2.94,1,1,MIL,,Top,MIL

In [27]:
ground = ['field_out','grounded_into_double_play','double_play',
'field_error','force_out','sac_fly']
ground_out = (cutoff['description'] == 'X') & (cutoff['events'].isin(ground))
cutoff.loc[ground_out, 'description'] = 'G'

K = ['strikeout']
strike_out = (cutoff['description'] == 'S') & (cutoff['events'].isin(K))
cutoff.loc[strike_out, 'description'] = 'K'

hits = ['single','double','triple','home_run']
hit = (cutoff['description'] == 'X') & (cutoff['events'].isin(hits))
cutoff.loc[hit, 'description'] = 'H'

walks = ['hit_by_pitch','walk']
walk = (cutoff['description'] == 'B') & (cutoff['events'].isin(walks))
cutoff.loc[walk, 'description'] = 'W'

cutoff

,pitch_name,game_date,batter,pitcher,player_name,description,events,zone,stand,p_throws,type,plate_x,plate_z,inning,pitch_number,home_team,away_team,inning_topbot,team
0,1,2022-10-05,672695,669203,"Burnes, Corbin",G,field_out,3.0,1,2,X,0.47,2.96,3,6,MIL,,Top,MIL
1,2,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,13.0,1,2,B,-0.70,0.84,3,5,MIL,,Top,MIL
2,5,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,12.0,1,2,B,2.09,2.88,3,4,MIL,,Top,MIL
3,4,2022-10-05,672695,669203,"Burnes, Corbin",S,NaN,14.0,1,2,S,0.09,1.36,3,3,MIL,,Top,MIL
4,1,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,14.0,1,2,B,1.69,1.42,3,2,MIL,,Top,MIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,3,2022-04-17,666185,676879,"Ashby, Aaron",G,field_out,14.0,2,1,X,0.84,2.33,1,5,MIL,,Top,MIL
310319,1,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,12.0,2,1,S,1.15,3.25,1,4,MIL,,Top,MIL
310320,3,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,4.0,2,1,S,-0.40,2.27,1,3,MIL,,Top,MIL
310321,3,2022-04-17,666185,676879,"Ashby, Aaron",B,NaN,13.0,2,1,B,-1.29,0.84,1,2,MIL,,Top,MIL
310322,5,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,3.0,2,1,S,0.71,2.94,1,1,MIL,,Top,MIL

In [14]:
cutoff[cutoff['description'] == 'K']

,pitch_name,game_date,batter,pitcher,player_name,description,events,zone,stand,p_throws,type,plate_x,plate_z,inning,pitch_number,home_team,away_team,inning_topbot
6,5,2022-10-05,608348,669203,"Burnes, Corbin",K,strikeout,6.0,2,2,S,0.55,2.19,3,6,MIL,AZ,Top
12,1,2022-10-05,642727,669203,"Burnes, Corbin",K,strikeout,13.0,1,2,S,-0.11,1.35,3,6,MIL,AZ,Top
26,1,2022-10-05,572233,669203,"Burnes, Corbin",K,strikeout,14.0,2,2,S,1.61,1.71,2,3,MIL,AZ,Top
29,1,2022-10-05,664983,669203,"Burnes, Corbin",K,strikeout,14.0,1,2,S,1.36,1.58,1,5,MIL,AZ,Top
34,4,2022-10-05,656976,669203,"Burnes, Corbin",K,strikeout,14.0,1,2,S,0.09,1.39,1,4,MIL,AZ,Top
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310244,4,2022-04-27,660636,676879,"Ashby, Aaron",K,strikeout,14.0,2,1,S,0.84,2.47,1,5,PIT,MIL,Bot
310251,5,2022-04-17,668800,676879,"Ashby, Aaron",K,strikeout,6.0,2,1,S,0.74,2.37,4,4,MIL,STL,Top
310274,3,2022-04-17,502671,676879,"Ashby, Aaron",K,strikeout,7.0,2,1,S,-0.81,1.83,3,3,MIL,STL,Top
310289,3,2022-04-17,669242,676879,"Ashby, Aaron",K,strikeout,13.0,2,1,S,-0.58,0.61,1,5,MIL,STL,Top
310294,5,2022-04-17,405395,676879,"Ashby, Aaron",K,strikeout,5.0,2,1,S,-0.08,2.28,1,7,MIL,STL,Top

In [28]:
cutoff['team'] = ""
cutoff.loc[cutoff['inning_topbot'] == "Top", 'away_team'] = ''
cutoff.loc[cutoff['inning_topbot'] == "Bot", "home_team"] = ''
cutoff['team'] = cutoff['home_team'] + cutoff['away_team']
cutoff

,pitch_name,game_date,batter,pitcher,player_name,description,events,zone,stand,p_throws,type,plate_x,plate_z,inning,pitch_number,home_team,away_team,inning_topbot,team
0,1,2022-10-05,672695,669203,"Burnes, Corbin",G,field_out,3.0,1,2,X,0.47,2.96,3,6,MIL,,Top,MIL
1,2,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,13.0,1,2,B,-0.70,0.84,3,5,MIL,,Top,MIL
2,5,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,12.0,1,2,B,2.09,2.88,3,4,MIL,,Top,MIL
3,4,2022-10-05,672695,669203,"Burnes, Corbin",S,NaN,14.0,1,2,S,0.09,1.36,3,3,MIL,,Top,MIL
4,1,2022-10-05,672695,669203,"Burnes, Corbin",B,NaN,14.0,1,2,B,1.69,1.42,3,2,MIL,,Top,MIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,3,2022-04-17,666185,676879,"Ashby, Aaron",G,field_out,14.0,2,1,X,0.84,2.33,1,5,MIL,,Top,MIL
310319,1,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,12.0,2,1,S,1.15,3.25,1,4,MIL,,Top,MIL
310320,3,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,4.0,2,1,S,-0.40,2.27,1,3,MIL,,Top,MIL
310321,3,2022-04-17,666185,676879,"Ashby, Aaron",B,NaN,13.0,2,1,B,-1.29,0.84,1,2,MIL,,Top,MIL
310322,5,2022-04-17,666185,676879,"Ashby, Aaron",S,NaN,3.0,2,1,S,0.71,2.94,1,1,MIL,,Top,MIL

In [33]:
cutoff

,pitch_name,game_date,batter,pitcher,player_name,description,zone,stand,p_throws,plate_x,plate_z,inning,pitch_number,team
0,1,2022-10-05,672695,669203,"Burnes, Corbin",G,3.0,1,2,0.47,2.96,3,6,MIL
1,2,2022-10-05,672695,669203,"Burnes, Corbin",B,13.0,1,2,-0.70,0.84,3,5,MIL
2,5,2022-10-05,672695,669203,"Burnes, Corbin",B,12.0,1,2,2.09,2.88,3,4,MIL
3,4,2022-10-05,672695,669203,"Burnes, Corbin",S,14.0,1,2,0.09,1.36,3,3,MIL
4,1,2022-10-05,672695,669203,"Burnes, Corbin",B,14.0,1,2,1.69,1.42,3,2,MIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310318,3,2022-04-17,666185,676879,"Ashby, Aaron",G,14.0,2,1,0.84,2.33,1,5,MIL
310319,1,2022-04-17,666185,676879,"Ashby, Aaron",S,12.0,2,1,1.15,3.25,1,4,MIL
310320,3,2022-04-17,666185,676879,"Ashby, Aaron",S,4.0,2,1,-0.40,2.27,1,3,MIL
310321,3,2022-04-17,666185,676879,"Ashby, Aaron",B,13.0,2,1,-1.29,0.84,1,2,MIL
310322,5,2022-04-17,666185,676879,"Ashby, Aaron",S,3.0,2,1,0.71,2.94,1,1,MIL

In [34]:
cutoff.to_csv('/Users/shkim/Desktop/data/Data.csv')